# AccessControl plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.cburris.bukkit.accesscontrol.AccessControl
name: AccessControl
version: 1.3
author: Charlie Burris
database: true
commands:
  stat:
    description: gets a player's stats from the server
    usage:
  ban:
    description: bans a player from the server
    usage: /ban <player_name>
  